name: iris
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - requests
  - tqdm
  - openai
  - accelerate
  - transformers
  - pytorch=2.5
  - google-generativeai
  - pip
  - pip:
    - docker
